apiVersion: v1 
kind: ConfigMap
metadata: 
  name: payment 
  namespace: roboshop
  labels:
    env: dev
    component: payment 
    project: roboshop

data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"

---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: payment 
  namespace: roboshop
  labels:
    env: dev
    component: payment 
    project: roboshop

spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      component: payment
      project: roboshop
  template:
    metadata:
      labels:
        env: dev
        component: payment 
        project: roboshop
    spec:
      containers:
        - name: payment 
          image: subbukola541/payment:1.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "800Mi"
              cpu: "1000m"

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2          
              
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 2
          
          
          envFrom:
            - configMapRef:
                name: payment


          
---
apiVersion: v1
kind: Service
metadata:  
  name: payment
  namespace: roboshop 
  labels:
    env: dev
    component: payment
    project: roboshop

spec:
  selector:
    env: dev
    component: payment
    project: roboshop
  ports:
    - targetPort: 8080 
      port: 8080
      protocol: TCP

      
      



