apiVersion: v1 
kind: ConfigMap
metadata: 
  name: user 
  namespace: roboshop
  labels:
    env: dev
    component: user 
    project: roboshop

data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

---

apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: user 
  namespace: roboshop
  labels:
    env: dev
    component: user 
    project: roboshop

spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      component: user
      project: roboshop
  template:
    metadata:
      labels:
        env: dev
        component: user 
        project: roboshop
    spec:
      containers:
        - name: user 
          image: subbukola541/user:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "800Mi"
              cpu: "1000m"

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2          
              
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 2
          
          
          envFrom:
            - configMapRef:
                name: user


          
---
apiVersion: v1
kind: Service
metadata:  
  name: user
  namespace: roboshop 
  labels:
    env: dev
    component: user
    project: roboshop

spec:
  selector:
    env: dev
    component: user
    project: roboshop
  ports:
    - targetPort: 8080 
      port: 8080
      protocol: TCP

      
      



